# Generated by Django 2.1.1 on 2019-11-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191126_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
