# Generated by Django 2.1.1 on 2019-11-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
