# Generated by Django 2.1.1 on 2019-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191127_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
