# Generated by Django 2.1.1 on 2019-12-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_notification_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='unix_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
