# Generated by Django 2.1.1 on 2019-12-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_blog_unix_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userfrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfrom', to=settings.AUTH_USER_MODEL)),
                ('userto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
