# Generated by Django 2.1.1 on 2019-12-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191210_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortner',
            old_name='url',
            new_name='blog',
        ),
    ]
