# Generated by Django 2.1.1 on 2019-12-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191225_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
