# Generated by Django 2.1.1 on 2019-12-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blog_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover_img',
        ),
    ]
