# Generated by Django 2.1.1 on 2019-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
