# Generated by Django 2.1.1 on 2020-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_readlater_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(default='5', max_length=128),
        ),
    ]
