# Generated by Django 2.1.1 on 2020-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200226_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='from_month',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='to_month',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='from_month',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='to_month',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
