# Generated by Django 2.1.1 on 2020-03-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200301_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='is_verified',
            new_name='present',
        ),
    ]
