# Generated by Django 2.1.1 on 2020-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200301_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='fieldofstudy',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
