# Generated by Django 2.1.1 on 2020-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_htmldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmldata',
            name='data',
            field=models.CharField(max_length=50000),
        ),
    ]
