# Generated by Django 2.1.1 on 2020-03-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_topblogs_topwriters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topwriters',
            old_name='blog',
            new_name='user',
        ),
    ]
