# Generated by Django 2.1.1 on 2020-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_profile_cover_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthread',
            name='commentthread',
            field=models.TextField(blank=True, null=True),
        ),
    ]
