# Generated by Django 2.1.1 on 2020-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20200524_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='clid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='views',
            name='src',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='views',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='views',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='views',
            name='utm_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
